project:
  type: book

book:
  title: |
    Code and data for "Evolution of pathogenesis-related proteins in plants"
  author: 
    - name: Wander Labaere
    - name: Aina Perez-Rodas
    - name: Yujin Cho
    - name: Jan Nawrocki
  date: "year"
  chapters:
    - index.qmd
    - chapters/01_identifying_PR_repertoires.qmd
    - chapters/02_comparison_of_repertoires_across_orders.qmd
    - chapters/get_gene_counts.qmd
    - chapters/gene_exp_cont_visualization.qmd
  
bibliography: bibliography.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source